config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    sessions:      'users/sessions'
  }

  get 'catalogs'  => 'pages#catalogs'
  get 'agreement' => 'pages#agreement'
  get 'privacy'   => 'pages#privacy'

  resource  :products,      only: :edit
  resources :products,      only: %i[show new create]

  resources :organizations, only: %i[create edit update show]

  resources :users,         only: [:update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  get '*unmatched_route', to: 'application#page_not_found'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  include Storext.model

  has_many :users, inverse_of: :organization
  has_many :products, inverse_of: :organization, dependent: :destroy

  validates :name, :inn, presence: true
  validates :inn,
            uniqueness: { message: I18n.t('errors.models.organization.attributes.inn.taken') }
  validates :inn, numericality: true, length: { in: 10..12 }

  scope :with_name, ->(name) { where('organizations.name ilike ?', "%#{name}%") }

  store_attributes :info do
    site String
    address String
    contact String
    phone String
    email String
  end

  # TODO
  def self.org_count
    Rails.cache.fetch('org_count', expires_in: 30.minutes) do
      count
    end
  end

  def contact_user
    users.where(contact: true).first
  end

  # TODO
  def update_user_phone
    return if user_phone.blank?

    contact_user.update_attribute(:phone, user_phone)
  end
end

app/models/page.rb
class Page
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  extend FriendlyId

  belongs_to :organization

  validates :name, :quantity, presence: true
  validates :quantity, numericality: true

  scope :with_name, ->(name) { where('products.name ilike ?', "%#{name}%") }

  friendly_id :slug_candidates, use: :slugged

  def self.all_count
    Rails.cache.fetch('prod_all_count', expires_in: 5.minutes) do
      count
    end
  end

  def slug_candidates
    [:name, %i[name organization_id]]
  end

  def normalize_friendly_id(text)
    text.to_slug.normalize! transliterations: %i[russian latin]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organization

  validates :name, :email, presence: true
  validates :email, uniqueness: true

  after_commit :send_welcome, on: :create

  def send_welcome
    WelcomeMailer.welcome_email(email, password).deliver_later
  end

  def parse_products
    return if file.blank?

    ParserService.new(file: file, user: self).parse_and_create
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session

  rescue_from StandardError do |e|
    response_for_standard_error
    ErrorNotificationService.email("#{e.class.name}: ", e)
  end

  def page_not_found
    respond_to do |format|
      format.html do
        # TODO: locale
        flash[:alert] = '404. Страница не найдена'
        redirect_to_back_or_to_root
      end
      format.any { head :not_found }
    end
  end

  def redirect_to_back_or_to_root(options = {})
    url = request.env['HTTP_REFERER']
    url ||= root_path
    session[:options] = options
    redirect_to url
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name inn org_name])
  end

  def response_for_standard_error
    text = I18n.t('global_errors.service_error')
    flash[:alert] = text
    redirect_to_back_or_to_root
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :authenticate_user!, except: %i[create show]
  before_action :find_org, only: %i[edit update show]

  def edit; end

  def update
    if @org.update(org_params)
      session[:errors] = nil
      flash[:notice] = 'Данные организации успешно обновлены'
      redirect_to @org
    else
      flash[:alert] = 'При обновлении возкнилки ошибки'
      session[:errors] = @org.errors.full_messages
      redirect_to edit_organization_path(@org)
    end
  end

  def show
    unless @org
      flash[:alert] = 'Такой организации не найдено.'
      redirect_to :back
    end
    @products = @org.products
  end

  private

  def find_org
    @org = Organization.find_by(id: params[:id])
  end

  def org_params
    params.require(:organization).permit(:name, :inn, :address, :email, :phone,
                                         :contact, :city, :description, :site, :user_phone)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @result = SearchService.new(params).make_search
  end

  def agreement; end

  def privacy; end

  def catalogs
    service = DocumentService.new
    @cats   = service.catalogs
    @certs  = service.certificates
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:new, :show]

  def new
    @form = UserForm.new User.new(contact: true)
    @form.organization = Organization.new

    @form.validate params.permit!.except('controller', 'action') if params.present?
  end

  def show
    @product = Product.friendly.find_by(slug: params[:id])
    unless @product
      # TODO: locale
      flash[:alert] =
        ['К сожалению, искомая позиция у производителя на данный момент отсутствует.',
         'Возможно она есть в наличии у других поставщиков.',
         'Воспользуйтесь поиском по порталу.']

      redirect_to root_path
      return
    end

    @org = @product.organization
    @products = @org.products
  end

  def create
    service = ParserService.new(file: params[:file], user: current_user)
    service.parse_and_create
    session[:errors] = nil

    if service.error.blank?
      # TODO: locale
      flash[:notice] = 'Подгрузка остатков прошла успешно'
      redirect_to current_user.organization if current_user
    else
      session[:errors] = service.error
      redirect_to new_product_path
    end
  end

  def edit
    @product = Product.new
    @org = current_user.organization
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    def create
      @form = UserForm.new User.new(contact: true)
      @form.organization = Organization.new

      if @form.validate permitted_params
        @form.save
        flash[:notice] = I18n.t('devise.registrations.signed_up_but_unconfirmed')
        redirect_to root_path
      else
        flash[:error] = @form.errors.messages
        respond_with @form
      end
    end

    protected

    def after_sign_up_path_for(_resource)
      edit_products_path
    end

    def permitted_params
      params.require(:user).permit(:name, :email, organization: %i[inn name city])
    end

    def organization_params
      params.require(:user).permit(organization: %i[inn name city])[:organization]
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    def new
      @form = UserForm.new User.new(contact: true)
      @form.organization = Organization.new
      @form.validate params
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'Данные успешно обновлены'
    else
      flash[:alert] = 'При обновлении возкнилки ошибки'
    end
    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:phone, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def elevated?
    controller_name == 'pages'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
- title = 'Элмуфта - кабельная арматура из наличия'
doctype html
html
  head
    title #{@page_title ?  @page_title+" | " + title : title}
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = javascript_include_tag 'application'
    = favicon_link_tag 'favicon.png'
    meta name="keywords" content="кабельные муфты, кабель муфта, кабельная муфта, муфта кабельный, кабельный кабель, норма кабель, муфты, электро муфты, тайко электроникс, te, tyco electronics, райхем, raychem, кабельная арматура, концевые муфты, единительные муфты, муфта polt, муфта polj, муфта квтп, муфта кнтп, муфта стп, термоусаживаемые муфты"
    meta name="description" content="Площадка для реализации кабельной арматуры. Муфты со складов по всей России и стран СНГ"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

  body
    #page
      .flash_msg
        - if flash[:notice]
          .box-message.box-message-success
            .box-message-content
              p
                = flash[:notice]
        - if !alert.blank?
          .box-message.box-message-error.center
            .box-message-content
              p
                - if alert.is_a? Array
                  -alert.each do |er|
                    p = er
                - else
                  = alert

      = yield :hero

      main class=(elevated? ? 'main' : 'main main-elevated')
        .container
          = yield
      .mobile-triggers
        a.mobile-trigger.form-filter-trigger href="#"
          i.fa.fa-search
          | Найти
        a.mobile-trigger.sidebar-wrap-trigger href="#"
          i.fa.fa-navicon
          | Фильтры
      footer.footer
        .container
          .row
            .col-xs-12
              .row
                .col-lg-6.col-md-6.col-xs-12
                  aside.widget.widget_categories.group
                    strong.ads__header.widget-title Разделы
                    ul.mtop_20
                      li
                        a href="/"  Главная
                      li
                        = link_to 'Добавить остатки', new_product_path
                      li
                        a href="/catalogs"  Каталоги
                .col-lg-6.col-md-6.col-xs-12
                  aside.widget.widget_text.group
                    strong.ads__header.widget-title Контакты
                    p.mtop_20
                      | По любым информационным вопросам просьба обращаться на email:
                      a href="mailto:info@elmyfta.ru"  info@elmyfta.ru
                    p
                      | По техническим вопросам и работе сайта:
                      a href="mailto:help@elmyfta.ru"  help@elmyfta.ru
              .footer-copy
                .row
                  .col-sm-12.col-xs-12
                    span
                      | Copyright
                      a href="mailto:info@elmyfta.ru"  ЭлМуфта
                      | &ndash; #{Time.current.year} г.
                    br
                    span
                      | Мы не занимаемся продажей. Информация о наличии и стоимости продукции не является публичной офертой.

                    span.pull-right
                      = link_to 'Пользовательское соглашение', agreement_path
                      br
                      = link_to 'Oбработка персональных данных', privacy_path
                  .col-sm-4.col-xs-12.text-right
                = render partial: 'shared/metrika'

app/views/organizations/show.slim
- @page_title = @org.name
= content_for :hero do
  .page-hero style=("background-image: url(#{asset_path 'hero-1.jpg'});")
    = render partial: 'shared/header'
    .container
      .row
        .col-xs-12
          .page-hero-content
            h1.page-title #{@org.name}
            .page-hero-details
              -if @org.city
                span.entry-location =@org.city

.row
  .col-xl-9.col-lg-8.col-xs-12
    .content-wrap
      - if current_user
        = link_to 'Редактировать профиль', edit_organization_path(current_user.organization), class: 'pull-right'
      article.entry
        .entry-content
          h2 Реквизиты организации:
          #job-manager-job-dashboard
            table.job-manager-jobs
              thead
                tr
                  th.job_title
                  th.filled
              tbody
                tr
                  td.job_title
                    | Название
                  td.filled
                    = @org.name
                tr
                  td.job_title
                    | Город
                  td.filled
                    = @org.city

                -if !@org.address.blank?
                  tr
                    td.job_title
                      | Адрес
                    td.filled
                      = @org.address
                tr
                  td.job_title
                    | ИНН
                  td.filled
                    = @org.inn

                - if !@org.phone.blank?
                  tr
                    td.job_title
                      | Телефон организации
                    td.filled
                      a.btn.btn-transparent#show_prd_org_phone href="#"  Показать
                      span.hidden_prd_org_phone = @org.phone


                - if !@org.site.blank?
                  tr
                    td.job_title
                      | Сайт
                    td.filled
                      = @org.site

          h2 Контакты:
          #job-manager-job-dashboard
            table.job-manager-jobs
              thead
                tr
                  th.job_title
                  th.filled
              tbody
                tr
                  td.job_title
                    | Имя
                  td.filled
                    = @org.contact
                - if @org.contact_user && !@org.contact_user.phone.blank?
                  tr
                    td.job_title
                      | Телефон
                    td.filled
                      a.btn.btn-transparent#show_prd_phone href="#"  Показать
                      span.hidden_prd_phone = @org.contact_user.phone

                - if !@org.email.blank?
                  tr
                    td.job_title
                      | Почта
                    td.filled
                      a.btn.btn-transparent#show_prd_email href="#"  Показать
                      span.hidden_prd_email = @org.email


          - if !@org.description.blank?
            hr
            h2 Об организации:
            p = @org.description

          hr
          h4 Остатки по продукции:
          .item-listing
            - if @products.empty?
              .list-item
                .list-item-main-info
                  p У организации пока нет данных о продукции.
            -else
              b = @products.count
              |  наименований
              - @products.each do |prod|
                .list-item
                  .list-item-main-info
                    p.list-item-title
                      = link_to prod.name, product_path(prod.slug)
                    .list-item-meta
                      = link_to @org.name, prod, class: "list-item-tag item-badge job-type-full-time"
                      / a.list-item-tag.item-badge.job-type-full-time href="" = prod.organization.city
                      span.list-item-company = @org.city
                  .list-item-secondary-info
                    p.list-item-location Количество
                    time.list-item-time = prod.quantity
                      / - if user_signed_in?
                      / - else
                      /   = link_to 'Узнать', new_user_session_path

  .col-xl-3.col-lg-4.col-xs-12
    .sidebar
      - unless current_user&.organization == @org
        aside.widget.widget_ci-apply-button-widget
          a.btn.btn-block.not-active href="#" target="_blank"
            | Подать заявку
      aside.widget.widget_ci-company-info-widget
        strong.ads__header.widget-title Информация об организации
        .card-info
          .card-info-media
            / figure.card-info-thumb
            /   img alt="Organization logo" src="images/company-logo.jpg" /
            .card-info-details
              p.card-info-title = @org.name
              p.card-info-title г. #{@org.city}
              p.card-info-link
                a href=""  = @org.site
          / .card-info-description
          /   p Краткое описание

coffee:
  prd_email = document.getElementById("show_prd_email")
  prd_phone = document.getElementById("show_prd_phone")
  prd_org_phone = document.getElementById("show_prd_org_phone")
  hidden_prd_email = document.getElementsByClassName("hidden_prd_email")[0]
  hidden_prd_phone = document.getElementsByClassName("hidden_prd_phone")[0]
  hidden_prd_org_phone = document.getElementsByClassName("hidden_prd_org_phone")[0]

  ready = () ->
    if hidden_prd_email then hidden_prd_email.style.display = 'none'
    if hidden_prd_phone then hidden_prd_phone.style.display = 'none'
    if hidden_prd_org_phone then hidden_prd_org_phone.style.display = 'none'

  document.addEventListener("DOMContentLoaded", ready);

  open_contact = () ->
    if prd_email then prd_email.style.display = 'none'
    if prd_phone then prd_phone.style.display = 'none'
    if prd_org_phone then prd_con_phone.style.display = 'none'
    if hidden_prd_email then hidden_prd_email.style.display = 'block'
    if hidden_prd_phone then hidden_prd_phone.style.display = 'block'
    if hidden_prd_org_phone then hidden_prd_con_phone.style.display = 'block'

  prd_email.onclick = (ev) ->
    ev.preventDefault()
    open_contact()

  prd_phone.onclick = (ev) ->
    ev.preventDefault()
    open_contact()

  prd_org_phone.onclick = (ev) ->
    ev.preventDefault()
    open_contact()

app/views/pages/_all_organizations.slim
h3.section-title
.item-listing
  - if organizations.empty?
    .list-item
      .list-item-main-info
        p К сожалению по Вашему запросу ничего не найдено.
  -else
    - organizations.each do |org|
      .list-item
        .list-item-main-info
          p.list-item-title
            = link_to "#{org.name}", organization_path(org.id)
          .list-item-meta
            span.list-item-company = org.city

br
  = will_paginate organizations

app/views/pages/_all_products.slim
h3.section-title
  - if params[:q].blank? && Product.all_count.positive?
    b = Product.all_count
    |  Наименований
  - else
    b = products.count
    |  Наименований
.item-listing
  - if products.empty?
    .list-item
      .list-item-main-info
        p К сожалению по Вашему запросу ничего не найдено.
  -else
    - products.each do |prod|
      .list-item

        .list-item-main-info
          p.list-item-title
            = link_to prod.name, product_path(prod.slug)
          .list-item-meta
            = link_to prod.organization.name, prod, class: "list-item-tag item-badge job-type-full-time"
            span.list-item-company = prod.organization.city

        .list-item-secondary-info
          p.list-item-location Количество
          time.list-item-time = prod.quantity

br
  = will_paginate products

app/views/products/_guest_organization.slim
= form_for(@form, url: '/users') do |f|
  .row
    .col-lg-6.col-xs-12
      h3 Реквизиты организации

      = f.fields_for @form.organization do |ff|
        .form-field
          label for="name"  Название организации*
          = ff.text_field :name, autofocus: true, placeholder: 'ООО Элмуфта', required: true
        .form-field
          label for="inn"  Инн*
          = ff.text_field :inn, placeholder: '10 - 12 цифер', required: true

        .form-field
          label for="inn"  Город*
          = ff.text_field :city, placeholder: 'Москва', required: true

        .form-field
          label for="address"  Адрес*
          = ff.text_field :address, placeholder: '101100, ул.Примерная, стр.9, оф.25', required: true

        .form-field
          label for="site"  Сайт
          = ff.text_field :site, placeholder: 'www.example.ru'

        .form-field
          label for="inn"  Об организации
          = ff.text_area :description, cols: 20, rows: 10

    .col-lg-6.col-xs-12
      h3 Контактное лицо
      .form-field
        label for="name"  Имя*
        = f.text_field :name, placeholder: 'Иванов Василий Петрович', required: true
      .form-field
        label for="email"  Email*
        = f.email_field :email, placeholder: 'example@mail.ru', required: true
        em будет выслано письмо с паролем

      .form-field
        label for=""  Телефон
        = f.text_field :phone, placeholder: '+7(999)-999-99-99'

      .form-field.center
        p
          | Нажимая кнопку «Создать профиль,
          br
          | Вы принимаете условия
          br
          = link_to "Пользовательского соглашения", agreement_path

      .form-field.center
        = f.submit 'Создать профиль'

app/views/products/_product.slim
- @products.each do |prod|
  .list-item
    .list-item-main-info
      p.list-item-title
        = link_to "#{prod.name} #{prod.mark}", product_path(prod.id)
      .list-item-meta
        = link_to prod.organization.name, prod, class: "list-item-tag item-badge job-type-full-time"
        / a.list-item-tag.item-badge.job-type-full-time href="" = prod.organization.city
        span.list-item-company = prod.organization.city
    .list-item-secondary-info
      p.list-item-location Количество
      - if user_signed_in?
        time.list-item-time = prod.quantity
      - else
        = link_to 'Узнать', new_user_session_path

app/views/products/edit.slim
= content_for :hero do
  .page-hero style=("background-image: url(#{asset_path 'hero-1.jpg'});")
    = render partial: 'shared/header'
    .container
      .row
        .col-xs-12
          .page-hero-content
            h1.page-title Добавить остатки по продукции
            .page-hero-details

.row
  .col-xl-10.offset-xl-1.col-lg-10.offset-lg-1.col-xs-12
    .content-wrap
      - if !flash[:alert].blank?
        .box-message.box-message-error
          .box-message-content
            - flash[:alert].each do |e|
              p
                = e
      br /

      = render partial: 'signed_organization'

app/views/products/show.slim
- @page_title = @product.name
= content_for :hero do
  .page-hero style=("background-image: url(#{asset_path 'hero-1.jpg'});")
    = render partial: 'shared/header'
    .container
      .row
        .col-xs-12
          .page-hero-content
            h1.page-title
              = @product.name
              span  -  #{@product.quantity} шт.
            .page-hero-details
              span.item-badge.job-type-full-time = @product.organization.name
              span.entry-location =@product.organization.city

.row
  .col-xl-9.col-lg-8.col-xs-12
    .content-wrap
      article.entry
        .entry-content
          h2 Контакты:
          #job-manager-job-dashboard
            table.job-manager-jobs
              thead
                tr
                  th.job_title
                  th.filled
              tbody
                tr
                  td.job_title
                    | Имя
                  td.filled
                    = @org.contact_user&.name
                - if @org.contact_user&.phone.present?
                  tr
                    td.job_title
                      | Телефон
                    td.filled
                      a.btn.btn-transparent#show_prd_con_phone href="#"  Показать
                      span.hidden_prd_con_phone = @org.contact_user.phone

                - if !@org.email.blank?
                  tr
                    td.job_title
                      | Почта
                    td.filled
                      a.btn.btn-transparent#show_prd_con_email href="#"  Показать
                      span.hidden_prd_con_email = @org.email

          h2 Реквизиты организации:
          #job-manager-job-dashboard
            table.job-manager-jobs
              thead
                tr
                  th.job_title
                  th.filled
              tbody
                tr
                  td.job_title
                    | Название
                  td.filled
                    = @org.name
                - if !@org.city.blank?
                  tr
                    td.job_title
                      | Город
                    td.filled
                      = @org.city
                - if !@org.address.blank?
                  tr
                    td.job_title
                      | Адрес
                    td.filled
                      = @org.address
                tr
                  td.job_title
                    | ИНН
                  td.filled
                    = @org.inn
                - if !@org.site.blank?
                  tr
                    td.job_title
                      | Сайт
                    td.filled
                      = @org.site

                - if !@org.phone.blank?
                  tr
                    td.job_title
                      | Телефон
                    td.filled
                      a.btn.btn-transparent#show_prd_phone href="#"  Показать
                      span.hidden_prd_phone = @org.phone

                - if !@org.email.blank?
                  tr
                    td.job_title
                      | Почта
                    td.filled
                      a.btn.btn-transparent#show_prd_email href="#"  Показать
                      span.hidden_prd_email = @org.email

          - if @org.description
            hr
            h2 Об организации:
            p
              = @org.description
          hr
          h4 Остатки по продукции:
          .item-listing
            - if @products.empty?
              .list-item
                .list-item-main-info
                  p К сожалению по Вашему запросу ничего не найдено.
            -else
              b = @products.count
              |  наименований
              - @products.each do |prod|
                .list-item
                  .list-item-main-info
                    p.list-item-title
                      = link_to "#{prod.name}", product_path(prod.slug)
                    .list-item-meta
                      = link_to @org.name, prod, class: "list-item-tag item-badge job-type-full-time"
                      span.list-item-company = @org.city
                  .list-item-secondary-info
                    p.list-item-location Количество
                    time.list-item-time = prod.quantity

  .col-xl-3.col-lg-4.col-xs-12
    .sidebar
      aside.widget.widget_ci-apply-button-widget
        a.btn.btn-block.not-active href="#" target="_blank"
          | Подать заявку
      aside.widget.widget_ci-company-info-widget
        strong.ads__header.widget-title Информация об организации
        .card-info
          .card-info-media
            .card-info-details
              p.card-info-title = @org.name
              p.card-info-title г. #{@org.city}
              p.card-info-link
                a href=""  = @org.site
      aside.widget.widget_ci-callout-widget
        .callout-wrapper
          .ads__header
            = image_tag 'favicon.png', size: '23'
            strong.ml-1 Блок рекламы
          br /
          p
            strong
              | По вопросам размещения рекламы
              br /
              a href="mailto:info@elmyfta.ru" info@elmyfta.ru
          a.btn.btn-round.btn-transparent href="mailto:info@elmyfta.ru"  Разместить рекламу

coffee:
  prd_email = document.getElementById("show_prd_email")
  prd_phone = document.getElementById("show_prd_phone")
  prd_con_email = document.getElementById("show_prd_con_email")
  prd_con_phone = document.getElementById("show_prd_con_phone")
  hidden_prd_email = document.getElementsByClassName("hidden_prd_email")[0]
  hidden_prd_phone = document.getElementsByClassName("hidden_prd_phone")[0]
  hidden_prd_con_email = document.getElementsByClassName("hidden_prd_con_email")[0]
  hidden_prd_con_phone = document.getElementsByClassName("hidden_prd_con_phone")[0]

  ready = () ->
    if hidden_prd_email then hidden_prd_email.style.display = 'none'
    if hidden_prd_phone then hidden_prd_phone.style.display = 'none'
    if hidden_prd_con_email then hidden_prd_con_email.style.display = 'none'
    if hidden_prd_con_phone then hidden_prd_con_phone.style.display = 'none'

  document.addEventListener("DOMContentLoaded", ready);

  open_contact = () ->
    if prd_email then prd_email.style.display = 'none'
    if prd_phone then prd_phone.style.display = 'none'
    if prd_con_email then prd_con_email.style.display = 'none'
    if prd_con_phone then prd_con_phone.style.display = 'none'
    if hidden_prd_email then hidden_prd_email.style.display = 'block'
    if hidden_prd_phone then hidden_prd_phone.style.display = 'block'
    if hidden_prd_con_email then hidden_prd_con_email.style.display = 'block'
    if hidden_prd_con_phone then hidden_prd_con_phone.style.display = 'block'

  handle_onclick = (el) ->
    el.onclick = (ev) ->
      ev.preventDefault()
      open_contact(ev)

  if prd_email
    handle_onclick(prd_email)

  if prd_phone
    handle_onclick(prd_phone)

  if prd_con_email
    handle_onclick(prd_con_email)

  if prd_con_phone
    handle_onclick(prd_con_phone)

app/views/shared/_header.slim
header.header
  .container
    .row
      .col-xs-12
        .mast-head
          h1.site-logo
            a href="/"
              = image_tag 'logo-elmyfta.png', style: '117x23'
          nav.nav
            ul.navigation-main
              li.menu-item-home.current-menu-item
                a href="/"  Главная
              li
                = link_to 'Добавить остатки', new_product_path

              li
                a href="/catalogs"  Тех.информация

              -if user_signed_in?
                li.menu-item-has-children
                  a href="#"
                    = current_user.organization.name
                  ul.sub-menu
                    li
                      = link_to 'Профиль организации', organization_path(current_user.organization)

                    li
                      = link_to 'Аккаунт', edit_user_registration_path

                    li
                      = link_to 'Добавить остатки', edit_products_path

                    li
                      =link_to 'Выйти', destroy_user_session_path, method: :delete
              -else
                li.menu-item-btn
                  = link_to "Войти", user_session_path
            /! #navigation
            a.mobile-nav-trigger href="#mobilemenu"
              i.fa.fa-navicon
              | Menu
          /! #nav
          #mobilemenu